### ISSUE TITLE
Create placeholder site

### ISSUE THREAD

**Issue by kacollins** [techlahoma/thunderplains-2024#1]
Include this info:
- 10/10 at okc convention center (Location may change but probably not)
- 10/10 evening after party will be OKC Tech++ at Dunlap Codding

See sites for previous years for inspiration:
- https://2023.thunderplainsconf.com/
- https://2021.thunderplainsconf.com/
- https://2020.thunderplainsconf.com/
- etc.

**Comment by vlucas** [comment]
This was done a while ago, but I didn't close this :)
