### ISSUE TITLE
Make the Verge and Viam logos look like the others

### ISSUE THREAD

**Issue by jsonthebson** [techlahoma/thunderplains-2024#14]
The other ones have background removed. here are the new files:
![Untitled design (1)](https://github.com/user-attachments/assets/3f72c9f5-f12e-4f60-8949-42bef0464e1a)
![Untitled design](https://github.com/user-attachments/assets/8a2dce61-6721-42dd-ab0f-a972503fe71d)

**Comment by kacollins** [comment]
I'll do this one!
