### ISSUE TITLE
Add volunteer link button

### ISSUE THREAD

**Issue by jsonthebson** [techlahoma/thunderplains-2024#19]
https://airtable.com/app1ec8sV8nSbCIAs/shrCDJcgZyBTw28X8

ask for clarification if you aren't sure about the design piece

**Comment by kacollins** [comment]
I'll do this! Planning to change the volunteer link to go to the [URL listed above](https://airtable.com/app1ec8sV8nSbCIAs/shrCDJcgZyBTw28X8) instead of the [current one](https://airtable.com/app1ec8sV8nSbCIAs/pagyxhjEDfCrZM2AE/form).
