### ISSUE TITLE
Add Kyle's proper info for his talk

### ISSUE THREAD

**Issue by jsonthebson** [techlahoma/thunderplains-2024#23]
Kyle Simpson has talk info now! Please list the way other speakers are listed

Title: Love/Hate: Upgrading to Web2.5 with Local-First
"Millions of developers have made their careers in the age of Web2, and most weren't even around for the days of Web1. Yet it's no shocking claim that Web2 still has a lot of problems that weigh it down, despite all the amazing advancements.

For years now, hopes of fixing those problems have largely hung on the promises of Web3 (blockchain and crypto). But just as other classic ""version upgrades"" (like Python 2 vs Python 3) lingered and stagnated, so too has Web3 largely failed yet to bridge the divide and pull along those of us stuck in Web2.

Big changes are usually the sum of many smaller changes. Web3 is too big a leap for many, so we need to look to more immediate and tangible evolutions.

Luckily, the web has a new way forward. Let's explore how local-first will upgrade the world to Web2.5."

**Comment by ChelseaHaldane** [comment]
working on this

**Comment by ChelseaHaldane** [comment]
Does this need to be in Kyle's section for his "about me" blurb?

**Comment by ChelseaHaldane** [comment]
I will turn this one back in. I do not have access to Sessionize
