### ISSUE TITLE
Add Jesse Harlin speaker card

### ISSUE THREAD

**Issue by melissacodes** [techlahoma/thunderplains-2024#28]
![jesse-harlin_720](https://github.com/user-attachments/assets/654c9d1d-b1c0-43c4-b42f-1e9810906065)

Owner and Chief Engineer of Simiancraft

Jesse Harlin (The Simian) is an Oklahoman programmer and software architect with decades of experience and several applications under his belt ranging across several industries. He is currently the Chief Engineer and Owner of Simiancraft, a software development agency, and has formerly been a community tech organizer, leader and cofounder for OKC.js, ThunderPlains and Techlahoma.

When he's not writing software, (or spending time with his family) he's probably composing new music or exploring new sounds on his synthesizers.

**Comment by pythoninthegrass** [comment]
I'll start working on this today. Will have it done by EOD at latest.

**Comment by vlucas** [comment]
This is on the site now. Thanks!
