### ISSUE TITLE
Add Cody Bromley speaker card

### ISSUE THREAD

**Issue by melissacodes** [techlahoma/thunderplains-2024#29]
![IMG_3848](https://github.com/user-attachments/assets/46c8a3dc-77f1-47e4-8910-8d21b45b5dc2)

Creative Technologist

Cody is a Product Strategist at Gitwit that specializes in helping companies navigate complex product development with technical research, prototyping and design thinking. Cody's recent experience includes implementing generative AI solutions for both startups and established organizations. In his spare time, Cody tinkers on his numerous side projects, including WX.Watch, a National Weather Service alert website and platform that crossposts alerts to Threads and the Fediverse. Cody lives in Tulsa with his wife and dog.

**Comment by crystalzipzap** [comment]
See PR #30

**Comment by vlucas** [comment]
This is on the site now. Thanks!
